os:
- linux
language: nix
sudo: required
env:
  global:
    secure: CWXeOsYnP1ySiSkiOlkaXBcwU1Zs88WjtvfGhciwzEqqHm+/krQ6ixi6bJjBD68N3mTttrSHp3RfniuY90CPBfsn/LDx7BtRvlv/RAAY+OOuqmn0z3kgvw4WrE6sFfjkveKN2NASiagt+TxSulV1Mt66qrZzvfKLzAtDzFPEL1UYds1lNhGkBOp0jWq4QPJkrS5PCT8kahIdWwbUlj8P9Imnwpt7IfqTujXIzPwFdKQei0b7o/t4VTAbFiA8qWOPDbRDlVJEBY8AQFvMNbiuouZbJAfx8B/S7Di/ZErN0PtBp5p3XLRphMMifbsOT30Gt2AtutDLOmWeVdyhfcmNo/0hWVdIuv7sfvcYPFY9cTGZHuuJAYdL/tzhddHuXNW9CQ68iNI4tKD1Zs7k9XbE/eGO92sH4DP6y/hA2gEBR86BHCohZDjIEvgPPXdUlAXrnMPQgTFVyVRBPCOg6AwLUazA0EkJEXKoelpuVzqPRe+k8JMV1wQAB1XZjh67gU9N2zPAfnnS5bktLrL1sBjC1v54Oqh+By9AbL1tnS9W8vAVBuFnX3nfl09MKsrzYmU+azCHGOydRnl5WjPr3DMMYMqS+nw1Ev6NI2G85y6IjyGTk4bGwD1jS+OnSSSxFSnN+PPcL2nTATV11Ryiqxo6Xlw6BPozcXRWoDGkfobNpHA=
